"use client";
import { FormEvent, useState } from "react";
import { AppShell } from "./app-shell";
import { Button, Card } from "./ui";
import { Icon } from "./icons";
import { useDemo } from "./demo-provider";
import type { Adviser, AdviserType, UserAdviserRelationship } from "@/lib/types";

const roles: Record<AdviserType, { eyebrow: string; title: string; description: string; add: string; find: string; timing: string; share: string[] }> = {
  MORTGAGE_BROKER: { eyebrow: "Your Mortgage Broker", title: "Mortgage Broker", description: "A mortgage broker can help when you're ready to discuss borrowing capacity, pre-approval and home loan options.", add: "Add my broker", find: "Find a broker", timing: "Most useful as you approach pre-approval and finance readiness.", share: ["Deposit progress", "Target buying timeframe", "Indicative target loan", "Preferred suburbs", "Contact details"] },
  BUYERS_AGENT: { eyebrow: "Your Buyer’s Agent", title: "Buyer’s Agent", description: "A buyer’s agent can help you search, assess and negotiate suitable properties.", add: "Add my buyer’s agent", find: "Find a buyer’s agent", timing: "Most useful when you are actively searching and ready to inspect or make offers.", share: ["Target suburbs", "Target price", "Property preferences", "Buying readiness", "Contact details"] },
  FINANCIAL_ADVISER: { eyebrow: "Your Financial Adviser", title: "Financial Adviser", description: "A financial adviser can help with broader savings, investment and financial strategy.", add: "Add my adviser", find: "Find an adviser", timing: "Useful throughout the journey if you want broader financial strategy support.", share: ["High-level savings progress", "Target buying timeframe", "Fund interest status", "Contact details"] },
  CONVEYANCER_SOLICITOR: { eyebrow: "Your Conveyancer / Solicitor", title: "Conveyancer / Solicitor", description: "Get help reviewing contracts and completing settlement when you’re ready.", add: "Add my conveyancer", find: "Find a conveyancer", timing: "Most useful when you are preparing to sign a contract.", share: ["Property details", "Purchase timeframe", "Contact details"] },
  ACCOUNTANT: { eyebrow: "Your Accountant", title: "Accountant", description: "Connect your accountant where tax or ownership structure advice may be relevant.", add: "Add my accountant", find: "Find an accountant", timing: "Useful where tax, ownership structure or investment questions arise.", share: ["High-level purchase goal", "Ownership questions", "Contact details"] },
};
const emphasised: AdviserType[] = ["MORTGAGE_BROKER", "BUYERS_AGENT", "FINANCIAL_ADVISER"];

export function AdvisersPage() {
  const { state, replace } = useDemo();
  const [modal, setModal] = useState<{ kind: "add" | "find" | "permissions" | "details"; type: AdviserType; adviserId?: string } | null>(null);
  const adviserFor = (type: AdviserType) => state.advisers.find((adviser) => adviser.adviserType === type && adviser.status === "CONNECTED");
  const requestFor = (type: AdviserType) => state.adviserIntroductionRequests.find((request) => request.adviserType === type && request.status === "REQUESTED");
  const primary = adviserFor("MORTGAGE_BROKER") ?? state.advisers[0];

  const changeAdviser = (adviser: Adviser) => replace({ ...state, advisers: state.advisers.map((item) => item.id === adviser.id ? { ...item, status: "INACTIVE" as const } : item), adviserRelationships: state.adviserRelationships.filter((relationship) => relationship.adviserId !== adviser.id) });

  return <AppShell title="Your advisers" subtitle="Build your team as you work towards buying your home. Connect the professionals you already use or ask Brickfloor to introduce someone when you need them.">
    {primary && <Card className="primary-adviser"><div className="adviser-identity"><span className="partner-logo">{primary.logoPlaceholder}</span><div><span className="eyebrow">{roles[primary.adviserType].eyebrow}</span><h2>{primary.firstName} {primary.lastName}</h2><p>{primary.company} <b>Connected</b></p></div></div><div className="primary-copy"><p>{primary.firstName} is available to support you as you progress towards buying your home. You can choose how and when you&apos;d like him involved.</p><p>When you&apos;re getting closer to buying, {primary.firstName} can help you understand your borrowing options and next steps.</p></div><AdviserPermissions adviser={primary} compact /><div className="adviser-actions"><Button variant="ghost" onClick={() => setModal({ kind: "details", type: primary.adviserType, adviserId: primary.id })}>View details</Button><Button variant="secondary" onClick={() => setModal({ kind: "permissions", type: primary.adviserType, adviserId: primary.id })}>Update permissions</Button><button className="text-action" onClick={() => changeAdviser(primary)}>Change adviser</button></div></Card>}
    <section className="team-section"><div><span className="eyebrow">Your professional team</span><h2>Add support when it becomes useful</h2><p>Connect professionals you already know or save a mock request for an introduction.</p></div><div className="adviser-role-grid">{emphasised.map((type) => <RoleCard key={type} type={type} adviser={adviserFor(type)} requested={Boolean(requestFor(type))} open={setModal} />)}</div><div className="supporting-roles">{(["CONVEYANCER_SOLICITOR", "ACCOUNTANT"] as AdviserType[]).map((type) => <RoleCard key={type} type={type} adviser={adviserFor(type)} requested={Boolean(requestFor(type))} open={setModal} compact />)}</div></section>
    <Card className="adviser-timing"><span className="eyebrow">When you may need each adviser</span><h2>Professional support across your journey</h2><div>{(Object.keys(roles) as AdviserType[]).map((type) => <article key={type}><span><Icon name={type === "MORTGAGE_BROKER" ? "wallet" : type === "BUYERS_AGENT" ? "home" : "users"} /></span><p><b>{roles[type].title}</b>{roles[type].timing}</p></article>)}</div><small>This is general educational guidance, not personal advice.</small></Card>
    {modal && <AdviserModal modal={modal} close={() => setModal(null)} />}
  </AppShell>;
}

function RoleCard({ type, adviser, requested, open, compact = false }: { type: AdviserType; adviser?: Adviser; requested: boolean; open: (value: { kind: "add" | "find" | "permissions" | "details"; type: AdviserType; adviserId?: string }) => void; compact?: boolean }) {
  const role = roles[type];
  return <Card className={`role-card ${compact ? "compact" : ""}`}><div className="role-card-head"><span className="role-icon"><Icon name={type === "MORTGAGE_BROKER" ? "wallet" : type === "BUYERS_AGENT" ? "home" : "users"} /></span><span className={`connection-status ${adviser ? "connected" : requested ? "requested" : ""}`}>{adviser ? "Connected" : requested ? "Introduction requested" : "Not connected"}</span></div><span className="eyebrow">{role.eyebrow}</span><h3>{adviser ? `${adviser.firstName} ${adviser.lastName}` : role.title}</h3>{adviser && <small>{adviser.company}</small>}<p>{role.description}</p>{adviser ? <div className="role-actions"><button onClick={() => open({ kind: "details", type, adviserId: adviser.id })}>View details</button><button onClick={() => open({ kind: "permissions", type, adviserId: adviser.id })}>Permissions</button></div> : <div className="role-actions"><button onClick={() => open({ kind: "add", type })}>{role.add}</button><button onClick={() => open({ kind: "find", type })}>{role.find}</button></div>}</Card>;
}

function AdviserPermissions({ adviser, compact = false }: { adviser: Adviser; compact?: boolean }) {
  const { state, replace } = useDemo();
  const relationship = state.adviserRelationships.find((item) => item.adviserId === adviser.id);
  if (!relationship) return null;
  const update = (key: keyof Pick<UserAdviserRelationship, "userConsentToProgressSharing" | "userConsentToReadinessNotification" | "userConsentToContact">) => replace({ ...state, adviserRelationships: state.adviserRelationships.map((item) => item.adviserId === adviser.id ? { ...item, [key]: !item[key] } : item) });
  const permissionLabels = compact ? [["userConsentToProgressSharing", "Keep my adviser updated on my progress"], ["userConsentToReadinessNotification", "Let my adviser know when I'm getting close to buying"], ["userConsentToContact", "Contact me when it may be a good time to speak"]] as const : [["userConsentToProgressSharing", "Share selected progress information"], ["userConsentToReadinessNotification", "Notify when my buying readiness changes"], ["userConsentToContact", "Allow my adviser to contact me"]] as const;
  return <div className={`permission-toggles ${compact ? "compact" : ""}`}>{permissionLabels.map(([key, label]) => <button key={key} className="toggle-row" onClick={() => update(key)} aria-pressed={relationship[key]}><span>{label}</span><span className={`toggle ${relationship[key] ? "on" : ""}`}><i /></span></button>)}</div>;
}

function AdviserModal({ modal, close }: { modal: { kind: "add" | "find" | "permissions" | "details"; type: AdviserType; adviserId?: string }; close: () => void }) {
  const { state, replace } = useDemo();
  const role = roles[modal.type];
  const adviser = state.advisers.find((item) => item.id === modal.adviserId);
  const [form, setForm] = useState({ firstName: "", lastName: "", company: "", email: "", phone: "" });
  const [consent, setConsent] = useState(false);
  const saveAdviser = (event: FormEvent) => { event.preventDefault(); const id = crypto.randomUUID(); const next: Adviser = { id, adviserType: modal.type, ...form, logoPlaceholder: `${form.firstName[0] ?? "A"}${form.lastName[0] ?? "D"}`.toUpperCase(), status: "CONNECTED" }; const relationship: UserAdviserRelationship = { adviserId: id, adviserType: modal.type, isPrimary: !state.advisers.some((item) => item.adviserType === modal.type && item.status === "CONNECTED"), relationshipSource: "USER_ADDED", connectedAt: new Date().toISOString(), userConsentToProgressSharing: false, userConsentToReadinessNotification: false, userConsentToContact: false, notes: "" }; replace({ ...state, advisers: [...state.advisers, next], adviserRelationships: [...state.adviserRelationships, relationship] }); close(); };
  const requestIntroduction = () => { if (!consent) return; replace({ ...state, adviserIntroductionRequests: [...state.adviserIntroductionRequests.filter((item) => item.adviserType !== modal.type), { id: crypto.randomUUID(), adviserType: modal.type, requestedAt: new Date().toISOString(), consentToShareSelectedProfile: true, status: "REQUESTED" }] }); close(); };
  return <div className="modal-backdrop" role="dialog" aria-modal="true"><Card className="modal adviser-modal"><button className="modal-close" onClick={close} aria-label="Close">×</button>{modal.kind === "add" && <><span className="eyebrow">Add your professional</span><h2>{role.add}</h2><form onSubmit={saveAdviser}><div className="field-grid">{(["firstName", "lastName", "company", "email", "phone"] as const).map((key) => <label className="field" key={key}><span>{key.replace(/([A-Z])/g, " $1").replace(/^./, (value) => value.toUpperCase())}</span><div><input required value={form[key]} type={key === "email" ? "email" : "text"} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /></div></label>)}</div><Button className="wide" type="submit">Save adviser</Button></form></>}{modal.kind === "find" && <><span className="eyebrow">Mock Brickfloor introduction</span><h2>{role.find}</h2><p>{role.description}</p><div className="sharing-preview"><b>Selected information</b>{role.share.map((item) => <span key={item}><Icon name="check" size={14} />{item}</span>)}</div><p className="privacy-note">Detailed household expenses, unrelated debts and private notes are not shared.</p><label className="confirm"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} /><span><Icon name="check" size={15} /></span><p>I give permission to share the selected profile information for this mock introduction.</p></label><Button className="wide" onClick={requestIntroduction}>{consent ? "Request introduction" : "Confirm permission to continue"}</Button></>}{modal.kind === "permissions" && adviser && <><span className="eyebrow">Sharing controls</span><h2>{adviser.firstName} {adviser.lastName}</h2><div className="sharing-preview"><b>Information relevant to your {role.title.toLowerCase()}</b>{role.share.map((item) => <span key={item}><Icon name="check" size={14} />{item}</span>)}</div><AdviserPermissions adviser={adviser} /><p className="privacy-note">Detailed household expenses, unrelated debts and private notes remain private.</p></>}{modal.kind === "details" && adviser && <><span className="eyebrow">{role.eyebrow}</span><h2>{adviser.firstName} {adviser.lastName}</h2><p>{adviser.company}<br />{adviser.email}<br />{adviser.phone}</p><p>{role.description}</p><Button variant="secondary" onClick={close}>Close</Button></>}</Card></div>;
}
