"use client";
import Link from "next/link";import {useEffect,useRef} from "react";import {Logo} from "./app-shell";import {Icon} from "./icons";import {trackEvent} from "@/lib/analytics";

const journey=[
  ["1","Set your home goal","Tell us where you want to buy, what you’re looking for and when you’d like to get there."],
  ["2","See what’s realistically within reach","We combine your deposit, savings rate and indicative borrowing capacity to show what may fit now and over the next 9 months."],
  ["3","Build your path there","Track your deposit and see how changes to your savings can bring more homes within reach sooner."],
  ["4","Get access to properties you might not otherwise see","Discover matched opportunities across new developments, pre-market properties and selected Brickfloor opportunities."],
];
const sources=[["New Developments","New homes supplied by participating developers and property partners."],["Pre-Market","Selected homes Brickfloor may know about before they are publicly listed."],["Brickfloor Opportunities","Selected properties where Brickfloor already has a commercial relationship with the property owner."]];

export function LandingPage(){const propertySection=useRef<HTMLElement>(null);useEffect(()=>{trackEvent("landing_page_view");const node=propertySection.current;if(!node)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){trackEvent("LANDING_PROPERTY_EXPLANATION_VIEWED");observer.disconnect()}},{threshold:.35});observer.observe(node);return()=>observer.disconnect()},[]);const start=()=>{trackEvent("start_plan");trackEvent("onboarding_started");trackEvent("LANDING_PRIMARY_CTA_CLICK");trackEvent("ONBOARDING_STARTED")};return <main className="welcome"><nav className="welcome-nav"><Logo/><Link href="/sign-in" onClick={()=>trackEvent("LANDING_SIGN_IN_CLICK")}>Sign in</Link></nav>
  <section className="welcome-hero"><div className="welcome-copy"><span className="hero-kicker"><Icon name="sparkle" size={16}/>Home Saver by Brickfloor</span><h1>Saving for a home? <em>Start getting exposure to property now.</em></h1><p>Build a clear plan for your first home, see what may come within reach, and explore an optional way to gain property exposure while you save.</p><div className="hero-actions"><Link className="button button-primary" href="/onboarding" onClick={start}>Build my home plan <Icon name="arrow"/></Link><a className="button button-secondary" href="#how-it-works">See how it works</a></div><p className="hero-reassurance"><Icon name="shield" size={15}/>Takes around 3 minutes. Your information stays private and you control what is shared.</p></div><HeroVisual/></section>
  <section className="landing-value"><div className="landing-heading"><span className="eyebrow">Three Home Saver benefits</span><h2>A clearer path into property</h2></div><div className="value-output-grid"><article><Icon name="wallet"/><small>Know where you stand</small><p>See what may be within reach now and how your buying position could change over the next 9 months.</p></article><article><Icon name="building"/><small>Get closer to property</small><p>Eligible users can choose to gain residential property exposure through the Brickfloor Fund while building towards their own home.</p></article><article><Icon name="home"/><small>Get access to opportunities</small><p>Discover matched new developments, pre-market homes and selected Brickfloor opportunities as they become relevant.</p></article></div></section>
  <section className="property-exposure"><div><span className="eyebrow">An optional pathway</span><h2>Start participating in property before you can afford a whole home</h2><p>Saving a home deposit can take years. During that time, property prices can move too.</p><p>Eligible Home Saver members may choose to invest part of their savings in the Brickfloor Residential Fund, providing exposure to residential property while continuing to work towards buying a home of their own.</p><strong>Gain exposure to residential property while you’re saving for one of your own.</strong><Link className="button button-primary" href="/investment-pledge" onClick={()=>trackEvent("FUND_EXAMPLE_OPENED")}>See how it could work <Icon name="arrow"/></Link><small>Investing is optional and involves risk. Eligibility and fund terms apply.</small></div><div className="path-comparison"><article><Icon name="wallet"/><span className="eyebrow">Save</span><h3>Cash savings</h3><p>Continue building your deposit through cash savings.</p><div>Cash savings <b>→</b> Deposit grows <b>→</b> Home purchase</div></article><article><Icon name="building"/><span className="path-badge">Optional investment pathway</span><h3>Save + optional property investment</h3><p>Eligible users may choose to invest part of their savings in the Brickfloor Residential Fund while continuing to build their home deposit.</p><div>Cash + optional fund <b>→</b> Build home goal assets <b>→</b> Home purchase</div></article><small>Investment values can rise or fall and money invested may not be suitable for a near-term home purchase.</small></div></section>
  <section className="landing-example"><div><span className="eyebrow">Illustrative example</span><h2>See how progress changes what may be possible</h2><p>Alex has:</p><ul><li><b>$68,400</b> saved</li><li><b>$2,200</b> monthly savings</li><li><b>$570,000</b> indicative borrowing capacity</li></ul></div><div className="example-timeline"><span><small>Today</small><b>6 homes</b><em>may be within reach</em></span><i/><span><small>In 6 months</small><b>11 homes</b><em>may be within reach</em></span><i/><span><small>In 9 months</small><b>15 homes</b><em>may be within reach</em></span></div><small>Illustrative example only. Property availability and borrowing capacity are not guaranteed.</small></section>
  <section className="journey-landing"><span className="eyebrow">How Home Saver works</span><h2>From your goal to homes coming within reach</h2><div>{journey.map((step,index)=><article className={index===3?"reward":""} key={step[0]}>{index===3&&<b className="priority-badge">Priority access</b>}<span>{step[0]}</span><h3>{step[1]}</h3><p>{step[2]}</p></article>)}</div></section>
  <section className="property-advantage" ref={propertySection}><div className="landing-heading"><span className="eyebrow">A broader view of the market</span><h2>More than a property search</h2><p>Home Saver doesn’t just show you listings. It matches your projected buying position with property opportunities that may become relevant as you get closer to buying.</p></div><div>{sources.map(([title,copy],index)=><article key={title}><span><Icon name={index===0?"building":index===1?"eye":"home"}/></span><h3>{title}</h3><p>{copy}</p></article>)}</div><p className="property-fit-note"><Icon name="check"/>We only show opportunities that may fit your projected buying position.</p></section>
  <section className="priority-cta"><span className="eyebrow">Home Saver community</span><h2>Get priority access as opportunities emerge</h2><p>Join Home Saver now and be among the first to hear about selected new developments, pre-market homes and Brickfloor opportunities that match your buying position.</p><Link className="button button-primary" href="/onboarding" onClick={()=>{trackEvent("LANDING_PRIORITY_ACCESS_CLICK");trackEvent("ONBOARDING_STARTED")}}>Join Home Saver <Icon name="arrow"/></Link><small>Priority access is not guaranteed and opportunities may not always be available.</small></section>
  <section className="landing-trust"><div><span className="privacy-mark"><Icon name="shield"/></span><span className="eyebrow">Privacy by design</span><h2>Your information, your control</h2><p>Your financial details are used to personalise your Home Saver experience.</p></div><div>{[["lock","Your personal information is not sold."],["users","You decide which advisers can see your progress."],["check","Introductions are only made with your permission."],["chart","Your financial details personalise your buying path."]].map(([icon,copy])=><p key={copy}><span><Icon name={icon}/></span>{copy}</p>)}</div></section>
  <section className="brickfloor-credibility"><div><span className="eyebrow">Powered by Brickfloor</span><h2>Building a better residential property journey</h2><p>Brickfloor is building a better way for Australians to save, invest and move through the residential property market.</p></div><div className="placeholder-logos"><span>Approved awards asset placeholder</span><span>Approved media recognition placeholder</span><span>Approved strategic partner placeholder</span></div></section>
  <footer className="landing-footer"><Logo/><p>Home Saver provides indicative planning information only. It is not financial, credit or property advice.</p><Link href="/onboarding" onClick={start}>See what’s within reach</Link></footer>
  </main>}

function HeroVisual(){return <div className="hero-visual"><div className="house-scene"><div className="sun"/><div className="cloud one"/><div className="cloud two"/><div className="house"><div className="roof"/><div className="house-body"><span className="window"/><span className="door"/></div></div><div className="tree">●</div><div className="ground"/></div><div className="float-card savings"><span><Icon name="chart"/></span><div><small>Projected buying position</small><strong>$640,000</strong><i>Indicative today</i></div></div><div className="float-card match"><span><Icon name="home"/></span><div><small>Coming within reach</small><strong>15 homes</strong><i>9-month outlook</i></div></div></div>}
