"use client";
import Link from "next/link";import {useEffect,useRef} from "react";import {Logo} from "./app-shell";import {Icon} from "./icons";import {trackEvent} from "@/lib/analytics";

const journey=[
  ["1","Set your home goal","Tell us where you want to buy, what you’re looking for and when you’d like to get there."],
  ["2","See what’s realistically within reach","We combine your deposit, savings rate and indicative borrowing capacity to show what may fit now and over the next 9 months."],
  ["3","Build your path there","Track your deposit and see how changes to your savings can bring more homes within reach sooner."],
  ["4","Get access to properties you might not otherwise see","Discover matched opportunities across new developments, pre-market properties and selected Brickfloor opportunities."],
];
const sources=[["New Developments","New homes supplied by participating developers and property partners."],["Pre-Market","Selected homes Brickfloor may know about before they are publicly listed."],["Brickfloor Opportunities","Selected properties where Brickfloor already has a commercial relationship with the property owner."]];

export function LandingPage(){const propertySection=useRef<HTMLElement>(null);useEffect(()=>{const node=propertySection.current;if(!node)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){trackEvent("LANDING_PROPERTY_EXPLANATION_VIEWED");observer.disconnect()}},{threshold:.35});observer.observe(node);return()=>observer.disconnect()},[]);const start=()=>{trackEvent("LANDING_PRIMARY_CTA_CLICK");trackEvent("ONBOARDING_STARTED")};return <main className="welcome"><nav className="welcome-nav"><Logo/><Link href="/sign-in" onClick={()=>trackEvent("LANDING_SIGN_IN_CLICK")}>Sign in</Link></nav>
  <section className="welcome-hero"><div className="welcome-copy"><span className="hero-kicker"><Icon name="sparkle" size={16}/>Home Saver by Brickfloor</span><h1>See the homes you’re <em>on track to afford.</em></h1><p>Home Saver turns your deposit, savings and indicative borrowing capacity into a personalised path to buying — and matches you with properties as they come within reach.</p><div className="hero-actions"><Link className="button button-primary" href="/onboarding" onClick={start}>See what’s within reach <Icon name="arrow"/></Link><Link className="button button-secondary" href="/sign-in" onClick={()=>trackEvent("LANDING_SIGN_IN_CLICK")}>Sign in</Link></div><p className="hero-reassurance"><Icon name="shield" size={15}/>Takes around 3 minutes. Your information stays private and you control what is shared.</p></div><HeroVisual/></section>
  <section className="landing-value"><div className="landing-heading"><span className="eyebrow">A personalised buying path</span><h2>Why tell us about your finances?</h2><p>The more we understand about your buying position, the better we can show you what may realistically come within reach — now and over the next 9 months.</p></div><div className="value-output-grid"><article><Icon name="wallet"/><small>Your projected buying position</small><strong>$640,000</strong><span>Indicative budget today</span></article><article><Icon name="home"/><small>Homes coming within reach</small><strong>6 → 15</strong><span>Today to nine months</span></article><article><Icon name="chart"/><small>A clearer path to your target</small><strong>March 2027</strong><span>Estimated readiness</span></article></div></section>
  <section className="landing-example"><div><span className="eyebrow">Illustrative example</span><h2>See how progress changes what may be possible</h2><p>Alex has:</p><ul><li><b>$68,400</b> saved</li><li><b>$2,200</b> monthly savings</li><li><b>$570,000</b> indicative borrowing capacity</li></ul></div><div className="example-timeline"><span><small>Today</small><b>6 homes</b><em>may be within reach</em></span><i/><span><small>In 6 months</small><b>11 homes</b><em>may be within reach</em></span><i/><span><small>In 9 months</small><b>15 homes</b><em>may be within reach</em></span></div><small>Illustrative example only. Property availability and borrowing capacity are not guaranteed.</small></section>
  <section className="journey-landing"><span className="eyebrow">How Home Saver works</span><h2>From your goal to homes coming within reach</h2><div>{journey.map((step,index)=><article className={index===3?"reward":""} key={step[0]}>{index===3&&<b className="priority-badge">Priority access</b>}<span>{step[0]}</span><h3>{step[1]}</h3><p>{step[2]}</p></article>)}</div></section>
  <section className="property-advantage" ref={propertySection}><div className="landing-heading"><span className="eyebrow">A broader view of the market</span><h2>More than a property search</h2><p>Home Saver doesn’t just show you listings. It matches your projected buying position with property opportunities that may become relevant as you get closer to buying.</p></div><div>{sources.map(([title,copy],index)=><article key={title}><span><Icon name={index===0?"building":index===1?"eye":"home"}/></span><h3>{title}</h3><p>{copy}</p></article>)}</div><p className="property-fit-note"><Icon name="check"/>We only show opportunities that may fit your projected buying position.</p></section>
  <section className="priority-cta"><span className="eyebrow">Home Saver community</span><h2>Get priority access as opportunities emerge</h2><p>Join Home Saver now and be among the first to hear about selected new developments, pre-market homes and Brickfloor opportunities that match your buying position.</p><Link className="button button-primary" href="/onboarding" onClick={()=>{trackEvent("LANDING_PRIORITY_ACCESS_CLICK");trackEvent("ONBOARDING_STARTED")}}>Join Home Saver <Icon name="arrow"/></Link><small>Priority access is not guaranteed and opportunities may not always be available.</small></section>
  <section className="landing-trust"><div><span className="privacy-mark"><Icon name="shield"/></span><span className="eyebrow">Privacy by design</span><h2>Your information, your control</h2><p>Your financial details are used to personalise your Home Saver experience.</p></div><div>{[["lock","Your personal information is not sold."],["users","You decide which advisers can see your progress."],["check","Introductions are only made with your permission."],["chart","Your financial details personalise your buying path."]].map(([icon,copy])=><p key={copy}><span><Icon name={icon}/></span>{copy}</p>)}</div></section>
  <section className="brickfloor-credibility"><div><span className="eyebrow">Powered by Brickfloor</span><h2>Building a better residential property journey</h2><p>Brickfloor is building a better way for Australians to save, invest and move through the residential property market.</p></div><div className="placeholder-logos"><span>Approved awards asset placeholder</span><span>Approved media recognition placeholder</span><span>Approved strategic partner placeholder</span></div></section>
  <footer className="landing-footer"><Logo/><p>Home Saver provides indicative planning information only. It is not financial, credit or property advice.</p><Link href="/onboarding" onClick={start}>See what’s within reach</Link></footer>
  </main>}

function HeroVisual(){return <div className="hero-visual"><div className="house-scene"><div className="sun"/><div className="cloud one"/><div className="cloud two"/><div className="house"><div className="roof"/><div className="house-body"><span className="window"/><span className="door"/></div></div><div className="tree">●</div><div className="ground"/></div><div className="float-card savings"><span><Icon name="chart"/></span><div><small>Projected buying position</small><strong>$640,000</strong><i>Indicative today</i></div></div><div className="float-card match"><span><Icon name="home"/></span><div><small>Coming within reach</small><strong>15 homes</strong><i>9-month outlook</i></div></div></div>}
