import type {AustralianState,DemoState,InventoryType,MarketStatus,Property} from "./types";
type Seed=[string,InventoryType,string,AustralianState,string,number,string,number,number,number,"New"|"Established",string|null,number|null,MarketStatus];
const seeds:Seed[]=[
["Parkside Quarter","NEW_DEVELOPMENT","Preston","VIC","3072",735000,"Townhouse",3,2,1,"New","Stockland",null,"COMING_SOON"],
["Riverline Residences","NEW_DEVELOPMENT","Parramatta","NSW","2150",790000,"Apartment",2,2,1,"New","Harbour Developments",null,"COMING_SOON"],
["Northshore Terraces","NEW_DEVELOPMENT","Chermside","QLD","4032",665000,"Townhouse",3,2,2,"New","Aster Projects",null,"PRE_MARKET"],
["Tuart Grove","NEW_DEVELOPMENT","Baldivis","WA","6171",610000,"House",4,2,2,"New","Western Living",null,"COMING_SOON"],
["Bowden Lane","NEW_DEVELOPMENT","Bowden","SA","5007",695000,"Townhouse",3,2,1,"New","Civic Homes",null,"COMING_SOON"],
["West Garden Collection","NEW_DEVELOPMENT","Werribee","VIC","3030",640000,"House",3,2,2,"New","Greenfield Group",null,"PRE_MARKET"],
["Bell Street Home","PRE_MARKET_MPG","Coburg","VIC","3058",755000,"House",3,2,1,"Established",null,720000,"PRE_MARKET"],
["Lygon Place Home","PRE_MARKET_MPG","Brunswick","VIC","3056",785000,"House",3,1,1,"Established",null,750000,"PRE_MARKET"],
["Nicholson Lane","PRE_MARKET_MPG","Footscray","VIC","3011",705000,"Townhouse",2,2,1,"Established",null,675000,"PRE_MARKET"],
["Eighth Avenue Home","PRE_MARKET_MPG","Maylands","WA","6051",650000,"House",3,1,2,"Established",null,620000,"PRE_MARKET"],
["Marine Parade Home","PRE_MARKET_MPG","Redcliffe","QLD","4020",715000,"Townhouse",3,2,2,"Established",null,680000,"PRE_MARKET"],
["Oakover Road","LIVE_MPG","Preston","VIC","3072",770000,"Townhouse",3,2,1,"Established",null,730000,"ON_MARKET"],
["George Street Residence","LIVE_MPG","Liverpool","NSW","2170",745000,"Apartment",3,2,1,"Established",null,710000,"AUCTION_SCHEDULED"],
["Pascoe Street Home","LIVE_MPG","Glenroy","VIC","3046",675000,"House",3,1,2,"Established",null,640000,"ON_MARKET"],
["Hamilton Road Home","LIVE_MPG","Chermside","QLD","4032",660000,"Townhouse",3,2,2,"Established",null,625000,"AUCTION_SCHEDULED"],
["Third Street Terrace","LIVE_MPG","Bowden","SA","5007",685000,"Townhouse",3,2,1,"Established",null,650000,"ON_MARKET"],
];
export const properties:Property[]=seeds.map((s,index)=>{const[title,inventoryType,suburb,state,postcode,priceGuide,propertyType,bedrooms,bathrooms,carSpaces,newOrEstablished,developerName,mpgFloorPrice,marketStatus]=s;const id=`demo-${index+1}`,image=`/property-${index%3+1}.svg`;return{propertyId:id,inventoryType,address:title,suburb,state,postcode,priceGuide,mpgFloorPrice,marketStatus,developerName,listingAgent:inventoryType==="NEW_DEVELOPMENT"?null:"Demo Listing Agent",expectedMarketDate:inventoryType==="PRE_MARKET_MPG"?"2026-11-15":null,auctionDate:marketStatus==="AUCTION_SCHEDULED"?"2026-10-24":null,expectedAvailability:inventoryType==="PRE_MARKET_MPG"?"Expected late 2026":"Available for demonstration enquiries",minimumDeposit:Math.round(priceGuide*.1),estimatedPurchaseCosts:Math.round(priceGuide*.04),active:true,featured:index<3,bedrooms,bathrooms,carSpaces,propertyType,newOrEstablished,landSize:propertyType==="House"?360:null,description:"Synthetic property retained only for explicit local development fallback.",image,images:[{url:image,alt:`Demo property in ${suburb}`}],matchScore:0,userProjectedMonthsUntilReach:null,accessLevel:inventoryType==="PRE_MARKET_MPG"?"Early Access":inventoryType==="LIVE_MPG"?"Floor Opportunity":"Standard",canMakeOffer:inventoryType==="PRE_MARKET_MPG",canRequestInspection:true,canTakeOverFloorPosition:inventoryType==="LIVE_MPG",isDemonstrationProperty:true,id,price:priceGuide,type:propertyType,beds:bedrooms,baths:bathrooms,parking:carSpaces,condition:newOrEstablished==="New"?"New build":"Established",benefit:"Government benefit eligibility has not been assessed",updatedAt:"2026-08-11T00:00:00Z"}});
export function propertyScore(property:Property,state:DemoState){let score=55;const priceDifference=Math.abs(property.priceGuide-state.goal.targetPrice)/Math.max(1,state.goal.targetPrice);score+=Math.max(0,20-Math.round(priceDifference*35));if(state.preference.suburbs.some(x=>x.toLowerCase()===property.suburb.toLowerCase()))score+=12;if(property.propertyType===state.preference.propertyType)score+=8;if(property.bedrooms>=state.preference.bedrooms)score+=5;if(state.preference.condition==="Either"||property.newOrEstablished===state.preference.condition.replace(" build",""))score+=5;return Math.min(99,score)}
export const navItems=[{href:"/dashboard",label:"Dashboard",icon:"home"},{href:"/my-plan",label:"My Plan",icon:"chart"},{href:"/property-matches",label:"Properties",icon:"building"},{href:"/investment-pledge",label:"Fund Interest",icon:"sparkle"},{href:"/advisers",label:"Advisers",icon:"users"},{href:"/profile",label:"Profile",icon:"user"}] as const;
