import type { DemoState } from "./types";
import { properties } from "./data";
import { calculateBuyingCapacity } from "./capacity";
export const defaultState:DemoState={
  user:{firstName:"Alex",lastName:"Morgan",email:"alex.morgan@email.com",mobile:"0412 345 678",ageRange:"25–34",state:"VIC",currentSuburb:"Brunswick",referralSource:"Mortgage broker",acquisitionChannel:"mortgage_broker",campaignName:"Broker nurture pilot",referralCode:"LM-JS-24",investorType:"FIRST_HOME_SAVER",adviceRequired:false,adviceStatus:"NOT_REQUIRED",fundInterestStatus:"INTERESTED",distributionChannel:"mortgage_broker",acquisitionPartner:"Loan Market"},
  financial:{currentSavings:68400,monthlySavings:2200,householdIncome:125000,partnerIncome:0,monthlyExpenses:3600,monthlyDebtRepayments:350,buyingWithSomeone:false,indicativeBorrowingCapacity:570000},
  goal:{targetPrice:800000,timeframe:"12–18 months",firstHomeBuyer:true,targetDate:""},
  preference:{suburbs:["Brunswick","Coburg","Preston"],propertyType:"House",bedrooms:3,condition:"Established",commutePreference:"Within 45 minutes of the CBD",schoolZonePreference:"Good local primary schools",lifestylePreference:"Walkable cafés and parks",preferredDeveloper:"",considerOffMarket:true,considerNewBuild:true,considerBrickfloorPrivate:true},
  buyerSignals:{livingSituation:"renting",currentHomeValue:0,currentMortgage:0,needsToSell:false,currentPropertySuburb:"",saleTimeframe:"",concernAboutSalePrice:false,interestedInMPG:false,mainBuyingBarrier:"deposit",motivation:"More space and long-term security",familyNeeds:"Planning for a family"},
  referralPartner:{id:"loan-market-john",organisationName:"Loan Market",contactName:"John Smith",partnerType:"mortgage_broker",email:"john@example.test",phone:"0400 000 101",referralCode:"LM-JS-24",logoPlaceholder:"LM",status:"active"},
  referralRelationship:{partnerId:"loan-market-john",referredAt:"2026-06-14",sourceCampaign:"Broker nurture pilot",relationshipStatus:"active",userConsentToProgressSharing:false,userConsentToReturnToPartner:false,userConsentToReconnect:false},
  originalReferringPartner:"Loan Market",originalReferringAdviser:"John Smith",
  advisers:[{id:"adviser-john-smith",adviserType:"MORTGAGE_BROKER",firstName:"John",lastName:"Smith",company:"Loan Market",email:"john@example.test",phone:"0400 000 101",logoPlaceholder:"LM",status:"CONNECTED"}],
  adviserRelationships:[{adviserId:"adviser-john-smith",adviserType:"MORTGAGE_BROKER",isPrimary:true,relationshipSource:"ACQUISITION_PARTNER",connectedAt:"2026-06-14",userConsentToProgressSharing:false,userConsentToReadinessNotification:false,userConsentToContact:false,notes:""}],
  adviserIntroductionRequests:[],
  broker:{mode:"none",name:"",company:"",email:"",phone:"",consent:false,shareContact:true},
  fund:{interested:true,amount:10000,availableDate:"Within 12 months",horizon:"5–7 years",priorityNotification:true,submitted:true},fundInterestStatus:"INTERESTED",
  contributions:[{id:"1",month:"2026-03",amount:2800},{id:"2",month:"2026-04",amount:3200},{id:"3",month:"2026-05",amount:3500},{id:"4",month:"2026-06",amount:3000},{id:"5",month:"2026-07",amount:3400},{id:"6",month:"2026-08",amount:3200}],
  savedPropertyIds:[1,7],enquiries:[],propertyActivities:[],propertyInventory:properties,notificationItems:[{id:"n1",title:"You’re getting closer",body:"You’re now within the next stage of your target deposit journey.",href:"/dashboard",read:false,createdAt:"2026-08-10"},{id:"n2",title:"Homes within reach",body:"3 demonstration homes may fit your projected buying position.",href:"/property-matches",read:false,createdAt:"2026-08-10"},{id:"n3",title:"Before Market match",body:"A new Before Market property matches your preferences.",href:"/property-matches",read:false,createdAt:"2026-08-09"},{id:"n4",title:"Your adviser team",body:"You may be approaching the point where speaking with your mortgage broker could be useful.",href:"/advisers",read:false,createdAt:"2026-08-08"}],onboardingStep:0,completed:false,notifications:{savings:true,properties:true,broker:true},thirdPartyIntroductions:false,
};
export function calculatePlan(state:DemoState){const targetDeposit=Math.round(state.goal.targetPrice*.2);const remaining=Math.max(0,targetDeposit-state.financial.currentSavings);const months=state.financial.monthlySavings>0?Math.ceil(remaining/state.financial.monthlySavings):0;const targetDate=new Date();targetDate.setMonth(targetDate.getMonth()+months);const progress=Math.min(100,Math.round(state.financial.currentSavings/Math.max(1,targetDeposit)*100));const annualCommitments=state.financial.monthlyExpenses*12+state.financial.monthlyDebtRepayments*12;const calculated=Math.max(0,Math.round(((state.financial.householdIncome+state.financial.partnerIncome)*4.8-annualCommitments*.65)/5000)*5000);const borrowing=state.financial.indicativeBorrowingCapacity||calculated;const capacity=borrowing+state.financial.currentSavings;const readiness=Math.min(98,Math.round(progress*.58+(state.preference.suburbs.length>=3?10:5)+(state.advisers.length?10:3)+(state.goal.firstHomeBuyer?7:4)+(state.financial.monthlySavings>0?15:0)));return{targetDeposit,remaining,months,progress,borrowing,capacity,gap:capacity-state.goal.targetPrice,readiness,targetDate:targetDate.toLocaleDateString("en-AU",{month:"long",year:"numeric"})}}
export const money=(n:number)=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD",maximumFractionDigits:0}).format(n);
export const projectedDepositAtMonths=(state:DemoState,months:number)=>state.financial.currentSavings+state.financial.monthlySavings*months;
export const projectedBuyingCapacityAtMonths=(state:DemoState,months:number)=>{const plan=calculatePlan(state);const projection=calculateBuyingCapacity({currentDeposit:state.financial.currentSavings,monthlySavings:state.financial.monthlySavings,indicativeBorrowingCapacity:plan.borrowing,depositPercentageGoal:.2,purchaseCostsEstimate:Math.max(25000,state.goal.targetPrice*.04)});return months===0?projection.today.estimatedBuyingBudget:months<=3?projection.threeMonths.estimatedBuyingBudget:months<=6?projection.sixMonths.estimatedBuyingBudget:projection.nineMonths.estimatedBuyingBudget};
export const monthsUntilPropertyWithinReach=(state:DemoState,price:number)=>{for(let month=0;month<=9;month++)if(projectedBuyingCapacityAtMonths(state,month)>=price)return month;return null};
export const reachLabel=(months:number|null)=>months===null?"Beyond the 9-month window":months===0?"Within reach now":`Within reach in ~${months<=3?3:months<=6?6:9} months`;
