import type {PropertyInput,PropertyRecord,PropertyUpdate} from "@/lib/types";import {createPublicSupabaseClient} from "@/lib/supabase/client";import {createAdminSupabaseClient} from "@/lib/supabase/server";import {normalisePropertyInput,propertyRecordToProperty} from "./propertyMapper";
export async function getActiveProperties(){const{data,error}=await createPublicSupabaseClient().from("properties").select("*").eq("is_active",true).order("is_featured",{ascending:false}).order("updated_at",{ascending:false});if(error)throw error;return(data as PropertyRecord[]).map(propertyRecordToProperty)}
export async function getPropertyById(id:string,includeInactive=false){const client=includeInactive?createAdminSupabaseClient():createPublicSupabaseClient();let query=client.from("properties").select("*").eq("id",id);if(!includeInactive)query=query.eq("is_active",true);const{data,error}=await query.maybeSingle();if(error)throw error;return data?propertyRecordToProperty(data as PropertyRecord):null}
export async function getAllPropertyRecords(){const{data,error}=await createAdminSupabaseClient().from("properties").select("*").order("updated_at",{ascending:false});if(error)throw error;return data as PropertyRecord[]}
export async function createProperty(input:PropertyInput){const{data,error}=await createAdminSupabaseClient().from("properties").insert(normalisePropertyInput(input)).select("*").single();if(error)throw error;return data as PropertyRecord}
export async function updateProperty(id:string,input:PropertyUpdate){const{data,error}=await createAdminSupabaseClient().from("properties").update(input).eq("id",id).select("*").single();if(error)throw error;return data as PropertyRecord}
export async function deleteProperty(id:string){const{error}=await createAdminSupabaseClient().from("properties").delete().eq("id",id);if(error)throw error}
export const setPropertyActive=(id:string,active:boolean)=>updateProperty(id,{is_active:active});export const setPropertyFeatured=(id:string,featured:boolean)=>updateProperty(id,{is_featured:featured});
export async function duplicateProperty(id:string){const{data,error}=await createAdminSupabaseClient().from("properties").select("*").eq("id",id).single();if(error)throw error;const{ id:_id,created_at:_created,updated_at:_updated,...copy}=data as PropertyRecord;void _id;void _created;void _updated;return createProperty({...copy,title:`${copy.title} (Copy)`,is_active:false,is_featured:false,external_reference:null})}
